mysite/blog/models.py
from datetime import datetime
from mysite import db


class Post(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    title = db.Column(db.String(100),     nullable=False)
    content = db.Column(db.Text,nullable=False)
    post_created = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)
    
    def __repr__(self):
        return f"{self.title},{self.content},{self.post_created},{self.user_id}"

mysite/blog/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField
from wtforms.validators import DataRequired

class MyForm(FlaskForm):
    name = StringField('name', validators=[DataRequired()])

mysite/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail

app = Flask(__name__)
#---------Bcrypt------------------
bcrypt = Bcrypt(app)

#----------LoginManager-------------
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.login_view = "auth.user_login"
login_manager.login_message_category = "success"

app.config['SECRET_KEY'] = 'a72c3251c8451aed32520c20b1ab7475'
#=======DATABASE==============
app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///test.db'
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
db = SQLAlchemy(app)

#------------Flask-Mail--------------
app.config['MAIL_SERVER'] = 'smtp.googlemail.com'
app.config['MAIL_PORT']  = 465
app.config['MAIL_USERNAME'] = 'surajblog47@gmail.com'
app.config['MAIL_PASSWORD'] = '88406439wp'
app.config['MAIL_USE_TLS'] = False
app.config['MAIL_USE_SSL'] = True

mail = Mail(app)

#----------App Register----------

from mysite.blog.views import blog
from mysite.auth.views import auth
from mysite.home.views import home

app.register_blueprint(blog,url_prefix='/blog')
app.register_blueprint(auth,url_prefix='/auth')
app.register_blueprint(home,url_prefix='/')

mysite/blog/views.py
from flask import Blueprint,render_template,request,flash,redirect,url_for
from flask_login import login_required,current_user
from .models import Post
from mysite import db


blog = Blueprint('blog',__name__)

@blog.route("/")
def home():
    post = Post.query.all()
    
    return render_template("Blog/index.html",user=current_user)


#-------------writepost---------------

@blog.route("/write/",methods=['GET','POST'])
@login_required
def write():
    if request.method == "POST":
        title = request.form['title']
        content = request.form['content']
        if not title:
            flash("Title dose not empty","danger")
            return redirect(url_for("blog.write"))
        elif not content:
            flash("Content dose not empty","danger")
            return redirect(url_for("blog.write"))
        else:
            post = Post(title=title,content=content,user_id=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash("Post hase been created","info")
            return redirect(url_for("blog.home"))
    return render_template("Blog/write_post.html")

#----------ReadSinglePost ------------
@blog.route("/read/<int:id>/")
def read_post(id):
    post = Post.query.filter_by(id=id).first()
    return render_template("Blog/read_post.html",post=post)

@login_required
@blog.route("/delete/<int:id>/")
def delete_post(id):
    if request.method == "GET":
        post = Post.query.filter_by(id=id).first()
        db.session.delete(post)
        db.session.commit()
        return redirect(url_for("blog.home"))
    return redirect(url_for("blog.home"))

mysite/home/views.py
from flask import Blueprint,render_template
from mysite.blog.models import Post


home = Blueprint("home",__name__)

@home.route("/")
def index():
    posts = Post.query.all()
    return render_template("home/index.html",post=posts)

mysite/templates/Blog/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container-bn">
    
     <div class="my-4 left">
       <button class="btn btn-primary">
         <a href="{{ url_for('blog.write')}}" >Write Post</a>
       </button>
     </div>
     {% for post in user.posts %}
               <div class="container-b inline">
      <p class="left">{{ post.title }}</p>
      <a href="{{url_for('blog.delete_post',id =post.id )}}"><img class="crud-image mx-2" src="{{ url_for('static',filename='image/blog/delete.png')}}" alt="" /></a><a class="" href="/"><img class="crud-image mx-2" src="{{ url_for('static',filename='image/blog/edit.png')}}" alt="" /></a>
    </div>
      {% endfor %}
   
  </div>
{% endblock %}

mysite/templates/Blog/read_post.html
{% extends "base.html" %}
{% block title %}{{ post.title }}{% endblock %}

    
{% block content %}

 <div class="container-f">
   <div class="container-bn">
          <div>
            <p class="left info">{{ post.author.name }}  <small class="">   {{ post.post_created.strftime('%Y-%m-%d')}}</small></p>
          </div>
          <div class="my-4">
          
            <h1 class="left ">
              <a class="link danger">{{ post.title }}</a>
            </h1>
          </div>
          <div class="my-4">
            <p class="left danger">{{ post.content }}</p>
          </div>
        </div>
       </div>
{% endblock %}

mysite/templates/Blog/write_post.html
{% extends 'base.html' %}
{% block content %}
<div class="container-f">

  <div class="container-bn">
    <h3 class="lg-heading">Write Post</h3>
<form method="POST" action="">
     <div class="my-4">
      <input placeholder="Post Title"class="title"type="" name="title" id="" value=""/>
     </div>
     <div class="my-4">
      <textarea placeholder="Post Content"class="textarea"name="content" id= rows="8" cols="40"></textarea>
     </div>
     <div class="left">
       <button class="btn btn-primary ">Post</button>
     </div>
    </form>
  </div>
 </div>
{% endblock %}

mysite/templates/Home/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}

  <div class="container-bn">
    
     {% for post in post %}
        <div class="container-b">
          <div>
            <p class="left danger">Posted by: {{ post.author.name }}<small class="">  {{ post.post_created.strftime('%Y-%m-%d')}}</small></p>
          </div>
          <div>
          
            <h3 class="left">
              <a href="{{ url_for('blog.read_post',id=post.id)}}" class="link danger">{{ post.title | truncate(50)  }}</a>
            </3>
          </div>
          <div class="my-4">
            <p class="left">{{ post.content | truncate(150)  }}</p>
            
          </div>
          
        </div>
      {% endfor %}

   
  </div>
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=<device-width></device-width>, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{{ url_for('static',filename='base.css') }}" type="text/css" media="all" />
   <link rel="stylesheet" href="{{ url_for('static',filename='layout.css') }}" type="text/css" media="all" />
 {% block head %}
 {% endblock %}
  <title>{% block title %}{% endblock %}</title>
 
</head>
<body>
  <nav>
    <label for="check">&equiv;</label>
    <input type="checkbox" name="check" id="check" value="" />
    <div class="logo">
      siteX
    </div>
    
    <ul>
    {% if current_user.is_authenticated %}
    {% set active_page = "/" %}
    
      <li><a href="/">home</a></li>
      <li><a href="{{ url_for('auth.home')}}">account</a></li>
      <li><a href="{{ url_for('blog.home')}}">blog</a></li>
      <li><a href="{{ url_for('auth.logout')}}">Logout</a></li>
     {% else %}
        <li><a href="/">home</a></li>
        <li><a href="{{ url_for('auth.user_signup')}}">signup</a></li>
        <li><a href="{{ url_for('auth.user_login')}}">singin</a></li>
     {% endif %}
    </ul>
  </nav>
 
<div class="container-f">
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}
</div>

{% block content %}{% endblock %}
</body>
</html>

mysite/templates/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="" content="">
        <title></title>
    </head>
    <body>
       HOME
    </body>
</html>